/* Speech Recognition HMM Grammar Vocabulary Description file
 * Copyright (C) 2003-2022 Sensory, Inc. All Rights Reserved.
 * 
 *
 *            source: ./tmp/3XKH1jh4O4fnD2h5cNpVr0mIxg13/1379234107/trecs-en_US_12-11-0-1_e3195f83f995ab8c7081adf15ed853aa951c9bae.snsr
 *           created: Fri Aug 26 12:07:04 2022
 *   min lib version: 6.5.0
 *   operating point: 9
 *  production ready: NO - development only
 *       license key: yes
 * recognition limit: 107
 *    duration limit: 11.43 hours
 *
 * Created by VoiceHub 1.23.0
 * Project: Sensory_Demo_-_Go_Silabs_wakeword
 *
 * This model will stop working after a preset number of recognition events
 * and/or a after a preset number of audio "bricks" have been processed.
 *
 * ------------------------- DO NOT USE IN A PRODUCT -------------------------
 */

//extern u32 gs_wakeword_grammarLabel;
#ifndef NETLABEL
#define NETLABEL
//extern u32 dnn_wakeword_netLabel;
#endif

/* The following phrases (Hex format) correspond to the word IDs emitted by the recognizer. */
#define WAKEWORD_PHRASE_COUNT 3
#define WAKEWORD_PHRASE_0 "SILENCE"	/* Legacy system phrase */
#define WAKEWORD_PHRASE_1 "\x67\x6F\x5F\x73\x61\x61\x79\x6C\x61\x62\x73"	/* Phrase: go_saaylabs */
#define WAKEWORD_PHRASE_2 "nota"	/* Legacy system phrase */


/* The following identifier was automatically generated by add_model.py */
#define MODEL_NAME "go_silabs"

/* Speech Recognition HMM Grammar file V60 for pc60 platform
 * Copyright (C) 2003-2022 Sensory, Inc. All Rights Reserved.
 * 
 *
 *            source: ./tmp/3XKH1jh4O4fnD2h5cNpVr0mIxg13/1379234107/trecs-en_US_12-11-0-1_e3195f83f995ab8c7081adf15ed853aa951c9bae.snsr
 *           created: Fri Aug 26 12:07:04 2022
 *   min lib version: 6.5.0
 *   operating point: 9
 *  production ready: NO - development only
 *       license key: yes
 * recognition limit: 107
 *    duration limit: 11.43 hours
 *
 * Created by VoiceHub 1.23.0
 * Project: Sensory_Demo_-_Go_Silabs_wakeword
 *
 * This model will stop working after a preset number of recognition events
 * and/or a after a preset number of audio "bricks" have been processed.
 *
 * ------------------------- DO NOT USE IN A PRODUCT -------------------------
 */

const char *wakeword_phrases[] = {WAKEWORD_PHRASE_0, WAKEWORD_PHRASE_1, WAKEWORD_PHRASE_2};
const unsigned short gs_wakeword_grammarLabel[] = {

   60,	 // 0x003c
  217,	 // 0x00d9
   24,	 // 0x0018
    0,	 // 0x0000
    1,	 // 0x0001
   25,	 // 0x0019
   32,	 // 0x0020
    0,	 // 0x0000
   32,	 // 0x0020
  179,	 // 0x00b3
  231,	 // 0x00e7
 1000,	 // 0x03e8
    0,	 // 0x0000
   27,	 // 0x001b
  200,	 // 0x00c8
 1000,	 // 0x03e8
  300,	 // 0x012c
    1,	 // 0x0001
   32,	 // 0x0020
   12,	 // 0x000c
    2,	 // 0x0002
    2,	 // 0x0002
   24,	 // 0x0018
   24,	 // 0x0018
    6,	 // 0x0006
    1,	 // 0x0001
    0,	 // 0x0000
    2,	 // 0x0002
    0,	 // 0x0000
    0,	 // 0x0000
    1,	 // 0x0001
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
28771,	 // 0x7063
  102,	 // 0x0066
  104,	 // 0x0068
  168,	 // 0x00a8
  192,	 // 0x00c0
  196,	 // 0x00c4
  200,	 // 0x00c8
  248,	 // 0x00f8
  296,	 // 0x0128
  320,	 // 0x0140
    0,	 // 0x0000
  328,	 // 0x0148
  332,	 // 0x014c
  334,	 // 0x014e
    0,	 // 0x0000
  430,	 // 0x01ae
 2100,	 // 0x0834
    2,	 // 0x0002
32769,	 // 0x8001
    1,	 // 0x0001
32768,	 // 0x8000
    5,	 // 0x0005
32772,	 // 0x8004
    4,	 // 0x0004
32771,	 // 0x8003
    8,	 // 0x0008
32775,	 // 0x8007
    7,	 // 0x0007
32774,	 // 0x8006
   11,	 // 0x000b
32778,	 // 0x800a
   10,	 // 0x000a
32777,	 // 0x8009
   14,	 // 0x000e
32781,	 // 0x800d
   13,	 // 0x000d
32780,	 // 0x800c
   17,	 // 0x0011
32784,	 // 0x8010
   16,	 // 0x0010
32783,	 // 0x800f
   20,	 // 0x0014
32787,	 // 0x8013
   19,	 // 0x0013
32786,	 // 0x8012
   23,	 // 0x0017
32790,	 // 0x8016
   22,	 // 0x0016
32789,	 // 0x8015
  103,	 // 0x0067
  111,	 // 0x006f
   95,	 // 0x005f
  115,	 // 0x0073
   97,	 // 0x0061
   97,	 // 0x0061
  121,	 // 0x0079
  108,	 // 0x006c
   97,	 // 0x0061
   98,	 // 0x0062
  115,	 // 0x0073
    0,	 // 0x0000
   23,	 // 0x0017
65535,	 // 0xffff
    0,	 // 0x0000
    0,	 // 0x0000
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
22144,	 // 0x5680
 3121,	 // 0x0c31
 3067,	 // 0x0bfb
 3310,	 // 0x0cee
 3210,	 // 0x0c8a
 3354,	 // 0x0d1a
 3182,	 // 0x0c6e
 3187,	 // 0x0c73
 3302,	 // 0x0ce6
 3308,	 // 0x0cec
 3332,	 // 0x0d04
 3548,	 // 0x0ddc
 3592,	 // 0x0e08
 3557,	 // 0x0de5
 3572,	 // 0x0df4
 3817,	 // 0x0ee9
 3925,	 // 0x0f55
 4044,	 // 0x0fcc
 4165,	 // 0x1045
 4022,	 // 0x0fb6
 3817,	 // 0x0ee9
 3730,	 // 0x0e92
 3583,	 // 0x0dff
 3355,	 // 0x0d1b
 3206,	 // 0x0c86
    1,	 // 0x0001
    7,	 // 0x0007
    1,	 // 0x0001
    3,	 // 0x0003
    1,	 // 0x0001
    2,	 // 0x0002
    1,	 // 0x0001
    5,	 // 0x0005
    1,	 // 0x0001
    4,	 // 0x0004
    1,	 // 0x0001
    6,	 // 0x0006
  173,	 // 0x00ad
    1,	 // 0x0001
    7,	 // 0x0007
    1,	 // 0x0001
    0,	 // 0x0000
65535,	 // 0xffff
 1770,	 // 0x06ea
   50,	 // 0x0032
  310,	 // 0x0136
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
   35,	 // 0x0023
  118,	 // 0x0076
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
   29,	 // 0x001d
  213,	 // 0x00d5
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
   34,	 // 0x0022
  170,	 // 0x00aa
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
   32,	 // 0x0020
  233,	 // 0x00e9
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
   50,	 // 0x0032
  310,	 // 0x0136
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
   34,	 // 0x0022
  271,	 // 0x010f
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
   40,	 // 0x0028
  143,	 // 0x008f
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
   25,	 // 0x0019
  896,	 // 0x0380
   21,	 // 0x0015
32768,	 // 0x8000
65535,	 // 0xffff
    0,	 // 0x0000
    0,	 // 0x0000
   20,	 // 0x0014
    2,	 // 0x0002
    0,	 // 0x0000
    0,	 // 0x0000
    0,	 // 0x0000
   19,	 // 0x0013
    3,	 // 0x0003
32770,	 // 0x8002
   16,	 // 0x0010
  385,	 // 0x0181
    9,	 // 0x0009
32772,	 // 0x8004
    2,	 // 0x0002
    0,	 // 0x0000
    2,	 // 0x0002
    8,	 // 0x0008
    5,	 // 0x0005
    3,	 // 0x0003
    0,	 // 0x0000
    1,	 // 0x0001
    7,	 // 0x0007
    6,	 // 0x0006
32774,	 // 0x8006
   16,	 // 0x0010
  131,	 // 0x0083
    3,	 // 0x0003
32776,	 // 0x8008
    5,	 // 0x0005
    0,	 // 0x0000
    4,	 // 0x0004
    2,	 // 0x0002
    8,	 // 0x0008
    6,	 // 0x0006
    0,	 // 0x0000
    3,	 // 0x0003
    1,	 // 0x0001
    9,	 // 0x0009
32778,	 // 0x800a
   16,	 // 0x0010
  644,	 // 0x0284
   15,	 // 0x000f
32780,	 // 0x800c
    8,	 // 0x0008
    0,	 // 0x0000
    1,	 // 0x0001
   14,	 // 0x000e
   11,	 // 0x000b
    9,	 // 0x0009
    0,	 // 0x0000
    4,	 // 0x0004
   13,	 // 0x000d
   12,	 // 0x000c
32782,	 // 0x800e
   16,	 // 0x0010
  259,	 // 0x0103
    6,	 // 0x0006
32784,	 // 0x8010
   11,	 // 0x000b
    0,	 // 0x0000
    5,	 // 0x0005
    5,	 // 0x0005
   14,	 // 0x000e
   12,	 // 0x000c
    0,	 // 0x0000
    3,	 // 0x0003
    4,	 // 0x0004
   15,	 // 0x000f
32786,	 // 0x8012
   16,	 // 0x0010
 1024,	 // 0x0400
   22,	 // 0x0016
32788,	 // 0x8014
   14,	 // 0x000e
    0,	 // 0x0000
    0,	 // 0x0000
   24,	 // 0x0018
   17,	 // 0x0011
   15,	 // 0x000f
    0,	 // 0x0000
    0,	 // 0x0000
   23,	 // 0x0017
   18,	 // 0x0012
32790,	 // 0x8016
   16,	 // 0x0010
  773,	 // 0x0305
   18,	 // 0x0012
32792,	 // 0x8018
   17,	 // 0x0011
    0,	 // 0x0000
    5,	 // 0x0005
   17,	 // 0x0011
   20,	 // 0x0014
   18,	 // 0x0012
    0,	 // 0x0000
    5,	 // 0x0005
   16,	 // 0x0010
   21,	 // 0x0015
32794,	 // 0x801a
   16,	 // 0x0010
  513,	 // 0x0201
   12,	 // 0x000c
32796,	 // 0x801c
   20,	 // 0x0014
    0,	 // 0x0000
    4,	 // 0x0004
   11,	 // 0x000b
   23,	 // 0x0017
   21,	 // 0x0015
    0,	 // 0x0000
    1,	 // 0x0001
   10,	 // 0x000a
65535,	 // 0xffff
32798,	 // 0x801e
};
